"""Stage 22: build the machine-readable feature-availability and leakage registry.

The registry is the single declarative source describing, for every column,
what it is, when it becomes knowable, whether it participates in constructing
the outcome, and therefore whether it may enter a model. Feature
configurations are derived from it (``ckd.features.registry``) rather than
maintained separately, so a classification cannot drift out of step with the
configuration that depends on it.

Leakage categories follow the taxonomy the manuscript uses:

``direct_outcome_copy``
    A renamed copy of the target.
``deterministic_outcome_derivative``
    A deterministic or near-deterministic function of the target or of the
    quantity defining it.
``post_diagnosis``
    Recorded only after the diagnosis exists; unavailable at index time.
``diagnostic_criterion_input``
    A legitimate contemporaneous measurement that is nevertheless an input to
    a KDIGO criterion for CKD itself, so using it risks incorporation bias.
    KDIGO 2024 defines CKD by GFR <60 mL/min/1.73 m2 *or* a marker of kidney
    damage, of which albuminuria (ACR >=30 mg/g) is the first listed. Serum
    creatinine is the input to the eGFR equation and therefore to the GFR
    limb; urine albumin is the albuminuria limb.
``possible_criterion_sediment``
    A urine sediment finding. KDIGO lists "urine sediment abnormalities" and
    "persistent haematuria" among the damage markers, so urinary red cells
    are criterion-adjacent; pyuria and bacteriuria point to infection rather
    than to CKD, and the release does not say which reading is intended.
    Separated from ``diagnostic_criterion_input`` because the incorporation
    risk is real but weaker and partly unverifiable.
``correlated_renal_biomarker``
    Tracks renal function and correlates with the outcome, but is **not** a
    KDIGO criterion for CKD. Blood urea is the clearest case: it appears
    nowhere in the KDIGO definition, and it is confounded by protein intake,
    catabolic state, hydration and gastrointestinal bleeding. Using such a
    variable is not incorporation bias; it is ordinary correlated
    information, and conflating the two overstates the leakage claim.
``consequence_of_advanced_disease``
    A downstream physiological consequence of established disease. Valid to
    measure, but its discriminative value comes from severity rather than
    from early detectability.
``legitimate_pre_index``
    Available before the diagnostic work-up and not part of the criterion.
``uncertain_provenance``
    Meaning, timing or coding could not be established from the release.

Output
------
data/feature_registry.csv                    the registry (source of truth)
reports/tables/table_47_feature_registry.csv publication copy
reports/tables/table_47_registry_summary.csv counts per category

Usage
-----
    python scripts/22_build_feature_registry.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from ckd.config import ensure_dirs, load_config, project_root  # noqa: E402
from ckd.data.clean import clean_dataset  # noqa: E402
from ckd.features.configs import FEATURE_CONFIGS, VARIABLES  # noqa: E402

#: Leakage category per column. Assignments are justified in `evidence`
#: below and, where they rest on a computed fact, that fact is regenerated by
#: the pipeline rather than asserted here.
CATEGORY = {
    # The outcome and its deterministic derivatives. Barred outright.
    "class": "direct_outcome_copy",
    "affected": "direct_outcome_copy",
    "stage": "deterministic_outcome_derivative",
    "grf": "deterministic_outcome_derivative",

    # Inputs to a KDIGO criterion for CKD. Both limbs of the definition are
    # represented in the released file: the GFR limb through creatinine, the
    # kidney-damage limb through urine albumin.
    "sc": "diagnostic_criterion_input",
    "al": "diagnostic_criterion_input",

    # Urine sediment findings. Criterion-adjacent, with the strength of the
    # link differing by finding and the release not saying which is meant.
    "rbc": "possible_criterion_sediment",
    "pc": "possible_criterion_sediment",
    "pcc": "possible_criterion_sediment",
    "ba": "possible_criterion_sediment",

    # Correlated with renal function, but not part of the CKD definition.
    "bu": "correlated_renal_biomarker",
    "sg": "correlated_renal_biomarker",
    "sod": "correlated_renal_biomarker",
    "pot": "correlated_renal_biomarker",

    # Downstream of established disease.
    "hemo": "consequence_of_advanced_disease",
    "pcv": "consequence_of_advanced_disease",
    "rbcc": "consequence_of_advanced_disease",
    "ane": "consequence_of_advanced_disease",

    # Available before the diagnostic work-up and not part of any criterion.
    "age": "legitimate_pre_index",
    "htn": "legitimate_pre_index",
    "dm": "legitimate_pre_index",
    "cad": "legitimate_pre_index",
    "appet": "legitimate_pre_index",
    "pe": "legitimate_pre_index",
    "bp (Diastolic)": "legitimate_pre_index",
    "bp limit": "legitimate_pre_index",
    "bgr": "legitimate_pre_index",
    "su": "legitimate_pre_index",
    "wbcc": "legitimate_pre_index",
}

#: Whether the column participates in constructing or staging the outcome.
CONSTRUCTS_OUTCOME = {
    "class": "is the outcome",
    "affected": "is the outcome, renamed",
    "stage": "banded directly from grf",
    "grf": "eGFR; the quantity by which CKD is defined and staged",
    "sc": "serum creatinine is the input to the eGFR equation, and eGFR <60 "
          "is the GFR limb of the KDIGO definition",
    "al": "urine albumin is the albuminuria limb of the KDIGO definition "
          "(ACR >=30 mg/g is the first-listed marker of kidney damage)",
    "rbc": "urinary red cells: KDIGO lists persistent haematuria and urine "
           "sediment abnormalities among the damage markers",
    "pc": "urine sediment finding; pyuria indicates infection rather than "
          "CKD, so criterion participation is weak and unverified",
    "pcc": "urine sediment finding; as for pc",
    "ba": "urine sediment finding; bacteriuria indicates infection",
    "bu": "blood urea is NOT a KDIGO criterion for CKD; it correlates with "
          "renal function but is confounded by protein intake, catabolism, "
          "hydration and gastrointestinal bleeding",
    "sg": "urine concentrating ability; not a KDIGO criterion",
    "sod": "serum sodium; not a KDIGO criterion in isolation",
    "pot": "serum potassium; not a KDIGO criterion in isolation",
}

#: Availability at the proposed index time (first clinical assessment).
AVAILABILITY = {
    "class": "not available (outcome)",
    "affected": "not available (outcome)",
    "stage": "not available (assigned after diagnosis)",
    "grf": "not available (computed as part of the diagnostic work-up)",
}

EVIDENCE = {
    "affected": "Cramer's V with class = 1.0 across all 200 rows "
                "(reports/data_quality_report.md)",
    "stage": "100% CKD at stages s3 and s5; Cramer's V with grf = 0.735 "
             "(table_24 / data quality report)",
    "grf": "eGFR bands; stage is a deterministic banding of it",
    "sc": "input to the CKD-EPI/MDRD equations, hence to the GFR limb of the "
          "KDIGO 2024 definition; recovered continuous values reach "
          "univariate ROC-AUC 0.946 (table_31_binning_cost)",
    "al": "KDIGO 2024 defines CKD by GFR <60 OR a marker of kidney damage, "
          "of which albuminuria (ACR >=30 mg/g) is the first listed. The "
          "released column is a semiquantitative reagent-strip grade, not a "
          "measured ACR: dipstick protein is a crude, concentration-dependent "
          "proxy that detects mainly albumin at higher grades and is not "
          "interchangeable with a quantified ratio. The incorporation risk is "
          "therefore real but weaker than for a measured ACR, and this "
          "distinction is why the variable has its own restricted "
          "configuration rather than being pooled with creatinine.",
    "bu": "blood urea appears nowhere in the KDIGO 2024 definition of CKD, "
          "neither in the GFR limb nor among the markers of kidney damage. "
          "An earlier version of this registry classified it as an "
          "incorporation risk; that was wrong and is corrected here.",
    "rbc": "KDIGO lists persistent haematuria and urine sediment "
           "abnormalities among the markers of kidney damage, so a urinary "
           "red-cell finding is criterion-adjacent. The release does not "
           "state whether the column is a urinary or a haematological "
           "reading, so the classification is provisional.",
    "hemo": "univariate ROC-AUC 0.968 (table_22); anaemia of CKD is a "
            "downstream consequence of reduced erythropoietin",
    "pcv": "univariate ROC-AUC 0.949 (table_22); tracks haemoglobin",
    "rbcc": "univariate ROC-AUC 0.876 (table_22)",
    "ane": "verified NOT a deterministic function of hemo bins "
           "(tests/test_encoders.py)",
}


def main() -> int:
    cfg = load_config()
    (tables_dir,) = ensure_dirs(cfg["paths"]["tables_dir"])
    result = clean_dataset()

    # Configuration membership, derived rather than typed.
    membership: dict[str, list[str]] = {}
    for name, config in FEATURE_CONFIGS.items():
        for feature in config.features:
            membership.setdefault(feature, []).append(name)

    missing = result.clean.isna().sum()
    n_rows = len(result.clean)

    rows = []
    for spec in VARIABLES:
        name = spec.name
        category = CATEGORY.get(name, "uncertain_provenance")
        if spec.uncertain and category == "legitimate_pre_index":
            category = "uncertain_provenance"
        in_configs = sorted(membership.get(name, []))
        valid_configs = [c for c in in_configs
                         if FEATURE_CONFIGS[c].valid_for_clinical_interpretation]
        rows.append({
            "variable": name,
            "human_readable": spec.description.split(",")[0].split(".")[0][:80],
            "dtype": "interval-encoded ordinal"
            if name in result.bin_map and len(result.bin_map[name]) > 2
            else "binary/categorical",
            "n_missing": int(missing.get(name, 0)),
            "missing_fraction": round(float(missing.get(name, 0)) / n_rows, 4),
            "n_levels": len(result.bin_map.get(name, [])),
            "measurement_time": "index assessment"
            if category in ("legitimate_pre_index", "incorporation_risk",
                            "consequence_of_advanced_disease")
            else "post-diagnosis",
            "available_at_index": AVAILABILITY.get(name, "available"),
            "constructs_or_stages_outcome": CONSTRUCTS_OUTCOME.get(name, "no"),
            "leakage_category": category,
            "cost_tier": spec.tier,
            "decision": "excluded from all valid configurations"
            if not valid_configs else "included",
            "config_membership": ";".join(in_configs) if in_configs else "none",
            "n_valid_configs": len(valid_configs),
            "uncertainty_flag": bool(spec.uncertain),
            "uncertainty_note": (spec.uncertainty_note or "")[:300],
            "evidence": EVIDENCE.get(name, spec.rationale[:200]),
        })

    registry = pd.DataFrame(rows)
    registry_path = project_root() / "data" / "feature_registry.csv"
    registry.to_csv(registry_path, index=False)
    print(f"wrote {registry_path} ({len(registry)} variables)")

    registry.to_csv(tables_dir / "table_47_feature_registry.csv", index=False)
    summary = (
        registry.groupby("leakage_category")
        .agg(n_variables=("variable", "size"),
             n_excluded=("n_valid_configs", lambda s: int((s == 0).sum())),
             variables=("variable", lambda s: ", ".join(sorted(s))))
        .reset_index()
        .sort_values("n_variables", ascending=False)
    )
    summary.to_csv(tables_dir / "table_47_registry_summary.csv", index=False)
    print("wrote table_47_feature_registry.csv and table_47_registry_summary.csv")
    print()
    print(summary[["leakage_category", "n_variables", "n_excluded"]]
          .to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
