"""Stage 24: emit LaTeX table fragments from generated results.

Manuscript tables must not be hand-typed: a number that is retyped can drift
from the analysis that produced it. This stage renders LaTeX fragments
directly from the committed CSVs into ``paper/generated/``, which the
manuscript then ``\\input``s.

Fragments produced
------------------
``leakage_taxonomy.tex``      feature-availability and leakage classification
``registry_summary.tex``      counts per leakage category
``restricted_featuresets.tex`` performance under registry-driven restrictions

Usage
-----
    python scripts/24_make_latex_tables.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from ckd.config import load_config, project_root  # noqa: E402

OUT = project_root() / "paper" / "generated"

#: Compact display names for the leakage categories.
CATEGORY_LABEL = {
    "direct_outcome_copy": "Direct outcome copy",
    "deterministic_outcome_derivative": "Deterministic derivative",
    "incorporation_risk": "Incorporation risk",
    "consequence_of_advanced_disease": "Consequence of advanced disease",
    "legitimate_pre_index": "Legitimate pre-index",
    "uncertain_provenance": "Uncertain provenance",
}

CATEGORY_ORDER = [
    "direct_outcome_copy",
    "deterministic_outcome_derivative",
    "incorporation_risk",
    "consequence_of_advanced_disease",
    "uncertain_provenance",
    "legitimate_pre_index",
]


def esc(text: str) -> str:
    """Escape the LaTeX specials that occur in this data."""
    return (
        str(text)
        .replace("\\", r"\textbackslash{}")
        .replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
        .replace("#", r"\#").replace("$", r"\$")
    )


def leakage_taxonomy(registry: pd.DataFrame) -> str:
    """One row per leakage category, listing its variables and the decision."""
    lines = [
        "% Generated by scripts/24_make_latex_tables.py -- do not edit.",
        r"\begin{table}[t]",
        r"\caption{Feature-availability and leakage taxonomy. Categories are "
        r"assigned in \texttt{data/feature\_registry.csv}, from which the "
        r"feature configurations are derived; a test asserts the two agree. "
        r"Prohibited categories cannot enter any clinically valid "
        r"configuration.}",
        r"\label{tab:leakage}",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{p{2.05cm}p{3.05cm}p{2.35cm}}",
        r"\toprule",
        r"\tabhead{Category} & \tabhead{Variables} & \tabhead{Decision} \\",
        r"\midrule",
    ]
    for category in CATEGORY_ORDER:
        subset = registry[registry["leakage_category"] == category]
        if subset.empty:
            continue
        variables = ", ".join(
            r"\texttt{" + esc(v) + "}" for v in sorted(subset["variable"])
        )
        n_excluded = int((subset["n_valid_configs"] == 0).sum())
        if n_excluded == len(subset):
            decision = r"\textbf{Excluded} from every valid configuration"
        elif category == "incorporation_risk":
            decision = "Retained; incorporation risk disclosed"
        elif category == "consequence_of_advanced_disease":
            decision = "Retained; severity-driven signal disclosed"
        elif category == "uncertain_provenance":
            decision = "Retained where tiering is conservative"
        else:
            decision = "Retained"
        lines.append(
            f"{CATEGORY_LABEL[category]} & {variables} & {decision} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def registry_summary(registry: pd.DataFrame) -> str:
    counts = (
        registry.groupby("leakage_category").size()
        .reindex(CATEGORY_ORDER).dropna().astype(int)
    )
    lines = [
        "% Generated by scripts/24_make_latex_tables.py -- do not edit.",
        r"\begin{tabular}{lr}",
        r"\toprule",
        r"\tabhead{Leakage category} & \tabhead{Variables} \\",
        r"\midrule",
    ]
    for category, n in counts.items():
        lines.append(f"{CATEGORY_LABEL[category]} & {int(n)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def restricted_featuresets(path: Path) -> str:
    if not path.is_file():
        return ""
    table = pd.read_csv(path)
    best = (table.sort_values("roc_auc", ascending=False)
            .groupby("featureset", as_index=False).first())
    order = [
        "full_valid (reference)",
        "minus consequences of advanced disease",
        "minus diagnostic-criterion inputs",
        "minus both",
        "pre-index available only",
    ]
    best["rank"] = best["featureset"].apply(
        lambda f: order.index(f) if f in order else 99)
    best = best.sort_values("rank")
    lines = [
        "% Generated by scripts/24_make_latex_tables.py -- do not edit.",
        r"\begin{table}[t]",
        r"\caption{Discrimination under registry-driven feature restriction. "
        r"Each row removes a leakage category from the full valid "
        r"configuration and re-runs the nested design. Best model per row; "
        r"95\% stratified bootstrap intervals.}",
        r"\label{tab:restricted}",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{p{3.0cm}ccc}",
        r"\toprule",
        r"\tabhead{Feature set} & \tabhead{$k$} & \tabhead{Model} & "
        r"\tabhead{ROC-AUC (95\% CI)} \\",
        r"\midrule",
    ]
    for _, r in best.iterrows():
        model = {"logreg": "Logistic", "svm": "SVM",
                 "random_forest": "RF"}.get(r["model"], r["model"])
        lines.append(
            f"{esc(r['featureset'])} & {int(r['n_features'])} & {model} & "
            f"{r['roc_auc']:.3f} ({r['roc_auc_ci_low']:.3f}--"
            f"{r['roc_auc_ci_high']:.3f}) \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def main() -> int:
    cfg = load_config()
    tables_dir = project_root() / cfg["paths"]["tables_dir"]
    OUT.mkdir(parents=True, exist_ok=True)

    registry = pd.read_csv(project_root() / "data" / "feature_registry.csv")
    written = []

    (OUT / "leakage_taxonomy.tex").write_text(
        leakage_taxonomy(registry), encoding="utf-8")
    written.append("leakage_taxonomy.tex")

    (OUT / "registry_summary.tex").write_text(
        registry_summary(registry), encoding="utf-8")
    written.append("registry_summary.tex")

    fragment = restricted_featuresets(
        tables_dir / "table_49_restricted_featuresets.csv")
    if fragment:
        (OUT / "restricted_featuresets.tex").write_text(fragment, encoding="utf-8")
        written.append("restricted_featuresets.tex")
    else:
        print("  note: table_49 not present; restricted_featuresets.tex skipped")

    for name in written:
        print(f"wrote paper/generated/{name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
