"""Stage 24: emit LaTeX table fragments from generated results.

Manuscript tables must not be hand-typed: a number that is retyped can drift
from the analysis that produced it. This stage renders LaTeX fragments
directly from the committed CSVs into ``paper/generated/``, which the
manuscript then ``\\input``s.

Fragments produced
------------------
``leakage_taxonomy.tex``      feature-availability and leakage classification
``registry_summary.tex``      counts per leakage category
``restricted_featuresets.tex`` performance under registry-driven restrictions

Usage
-----
    python scripts/24_make_latex_tables.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from ckd.config import load_config, project_root  # noqa: E402

OUT = project_root() / "paper" / "generated"
TABLES = project_root() / "reports" / "tables"

#: Compact display names for the leakage categories.
CATEGORY_LABEL = {
    "direct_outcome_copy": "Direct outcome copy",
    "deterministic_outcome_derivative": "Deterministic derivative",
    "diagnostic_criterion_input": "KDIGO criterion input",
    "possible_criterion_sediment": "Urine sediment (possible criterion)",
    "correlated_renal_biomarker": "Correlated renal biomarker",
    "consequence_of_advanced_disease": "Consequence of advanced disease",
    "legitimate_pre_index": "Legitimate pre-index",
    "uncertain_provenance": "Uncertain provenance",
}

CATEGORY_ORDER = [
    "direct_outcome_copy",
    "deterministic_outcome_derivative",
    "diagnostic_criterion_input",
    "possible_criterion_sediment",
    "correlated_renal_biomarker",
    "consequence_of_advanced_disease",
    "uncertain_provenance",
    "legitimate_pre_index",
]


def esc(text: str) -> str:
    """Escape the LaTeX specials that occur in this data."""
    return (
        str(text)
        .replace("\\", r"\textbackslash{}")
        .replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
        .replace("#", r"\#").replace("$", r"\$")
    )


def leakage_taxonomy(registry: pd.DataFrame) -> str:
    """One row per leakage category, listing its variables and the decision."""
    lines = [
        "% Generated by scripts/24_make_latex_tables.py -- do not edit.",
        r"\begin{table}[t]",
        r"\caption{Feature-availability and leakage taxonomy. Categories are "
        r"assigned in \texttt{data/feature\_registry.csv}, from which the "
        r"feature configurations are derived; a test asserts the two agree. "
        r"Prohibited categories cannot enter any clinically valid "
        r"configuration.}",
        r"\label{tab:leakage}",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{p{2.05cm}p{3.05cm}p{2.35cm}}",
        r"\toprule",
        r"\tabhead{Category} & \tabhead{Variables} & \tabhead{Decision} \\",
        r"\midrule",
    ]
    for category in CATEGORY_ORDER:
        subset = registry[registry["leakage_category"] == category]
        if subset.empty:
            continue
        variables = ", ".join(
            r"\texttt{" + esc(v) + "}" for v in sorted(subset["variable"])
        )
        n_excluded = int((subset["n_valid_configs"] == 0).sum())
        if n_excluded == len(subset):
            decision = r"\textbf{Excluded} from every valid configuration"
        elif category == "diagnostic_criterion_input":
            decision = "Retained; incorporation risk disclosed"
        elif category == "possible_criterion_sediment":
            decision = "Retained; possible incorporation disclosed"
        elif category == "correlated_renal_biomarker":
            decision = "Retained; not a diagnostic criterion"
        elif category == "consequence_of_advanced_disease":
            decision = "Retained; severity-driven signal disclosed"
        elif category == "uncertain_provenance":
            decision = "Retained where tiering is conservative"
        else:
            decision = "Retained"
        lines.append(
            f"{CATEGORY_LABEL[category]} & {variables} & {decision} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def registry_summary(registry: pd.DataFrame) -> str:
    counts = (
        registry.groupby("leakage_category").size()
        .reindex(CATEGORY_ORDER).dropna().astype(int)
    )
    lines = [
        "% Generated by scripts/24_make_latex_tables.py -- do not edit.",
        r"\begin{tabular}{lr}",
        r"\toprule",
        r"\tabhead{Leakage category} & \tabhead{Variables} \\",
        r"\midrule",
    ]
    for category, n in counts.items():
        lines.append(f"{CATEGORY_LABEL[category]} & {int(n)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def restricted_featuresets(path: Path) -> str:
    if not path.is_file():
        return ""
    table = pd.read_csv(path)
    best = (table.sort_values("roc_auc", ascending=False)
            .groupby("featureset", as_index=False).first())
    order = [
        "full_valid (reference)",
        "minus criterion inputs only (strict)",
        "minus all incorporation-risk variables",
        "minus consequences of advanced disease",
        "minus incorporation and consequences",
        "pre-index available only",
        "minimal low-cost conservative",
    ]
    best["rank"] = best["featureset"].apply(
        lambda f: order.index(f) if f in order else 99)
    # Rows not named in ``order`` belong to the supplement's full table, not
    # to the main text; showing all ten here would not fit the column.
    best = best[best["rank"] < 99].sort_values("rank")
    lines = [
        "% Generated by scripts/24_make_latex_tables.py -- do not edit.",
        r"\begin{table}[t]",
        r"\caption{Discrimination under registry-driven feature restriction. "
        r"Each row removes a leakage category from the full valid "
        r"configuration and re-runs the nested design. Categories are "
        r"assigned against the KDIGO definition of CKD, so the "
        r"incorporation rows remove \emph{both} limbs of that definition "
        r"---\,creatinine and urine albumin\,--- not creatinine alone. Best "
        r"model per row; 200 unique patients; 95\% stratified patient-level "
        r"bootstrap intervals. The full ten-configuration table, with "
        r"PR-AUC, specificity and Brier score, is in the supplement.}",
        r"\label{tab:restricted}",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{p{2.7cm}ccc}",
        r"\toprule",
        r"\tabhead{Feature set} & \tabhead{$k$} & "
        r"\tabhead{ROC-AUC (95\% CI)} & \tabhead{Sens.} \\",
        r"\midrule",
    ]
    for _, r in best.iterrows():
        lines.append(
            f"{esc(r['featureset'])} & {int(r['n_features'])} & "
            f"{r['roc_auc']:.3f} ({r['roc_auc_ci_low']:.3f}--"
            f"{r['roc_auc_ci_high']:.3f}) & {r['sensitivity']:.3f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def restricted_full(path: Path) -> str:
    """All ten configurations with the full metric set, for the supplement."""
    if not path.is_file():
        return ""
    table = pd.read_csv(path)
    best = (table.sort_values("roc_auc", ascending=False)
            .groupby("featureset", as_index=False).first())
    best = best.sort_values("roc_auc", ascending=False)
    lines = [
        "% Generated by scripts/24_make_latex_tables.py -- do not edit.",
        "% Source: reports/tables/table_49_restricted_featuresets.csv",
        r"\begin{table*}[t]",
        r"\caption{Every registry-derived configuration, best model per row. "
        r"200 unique patients (128 cases); 95\% stratified patient-level "
        r"bootstrap intervals. \emph{Saturated} marks a configuration whose "
        r"lower interval bound is at or above 0.99, i.e.\ one retaining no "
        r"measurable headroom on this sample.}",
        r"\label{tab:restrictedfull}",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{p{4.4cm}cl ccccc c}",
        r"\toprule",
        r"\tabhead{Feature set} & \tabhead{$k$} & \tabhead{Model} & "
        r"\tabhead{ROC-AUC (95\% CI)} & \tabhead{PR-AUC} & "
        r"\tabhead{Sens.} & \tabhead{Spec.} & \tabhead{Brier} & "
        r"\tabhead{Sat.} \\",
        r"\midrule",
    ]
    for _, r in best.iterrows():
        model = {"logreg": "Logistic", "svm": "SVM",
                 "random_forest": "RF"}.get(r["model"], r["model"])
        lines.append(
            f"{esc(r['featureset'])} & {int(r['n_features'])} & {model} & "
            f"{r['roc_auc']:.3f} ({r['roc_auc_ci_low']:.3f}--"
            f"{r['roc_auc_ci_high']:.3f}) & {r['pr_auc']:.3f} & "
            f"{r['sensitivity']:.3f} & {r['specificity']:.3f} & "
            f"{r['brier']:.3f} & "
            f"{'yes' if r['saturated'] else 'no'} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""]
    return "\n".join(lines)


def casemix_simulation(path: Path) -> str:
    """Measured performance under re-weighted case mixes, for the supplement."""
    if not path.is_file():
        return ""
    table = pd.read_csv(path)
    lines = [
        "% Generated by scripts/24_make_latex_tables.py -- do not edit.",
        "% Source: reports/tables/table_54_casemix_simulation.csv",
        r"\begin{table*}[t]",
        r"\caption{Measured performance under target severity distributions, "
        r"models held fixed and out-of-fold predictions re-weighted. "
        r"\textbf{Exploratory resampling, not prospective evidence.} "
        r"Intervals are Monte Carlo only and do not reflect the thinness of "
        r"the support: the benchmark holds 9 stage-1 and 12 stage-2 cases, "
        r"so early-heavy targets reuse a few patients many times, as the "
        r"last two columns show.}",
        r"\label{tab:casemixsim}",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{p{2.6cm}p{3.3cm}cccc}",
        r"\toprule",
        r"\tabhead{Configuration} & \tabhead{Target mix} & "
        r"\tabhead{Early frac.} & \tabhead{ROC-AUC (MC 95\%)} & "
        r"\tabhead{Sens.} & \tabhead{Distinct / max reuse} \\",
        r"\midrule",
    ]
    for _, r in table.iterrows():
        lines.append(
            f"{esc(r['config'].replace('_model', ''))} & "
            f"{esc(r['target_mix'])} & {r['early_case_fraction']:.2f} & "
            f"{r['roc_auc']:.3f} ({r['roc_auc_mc_low']:.3f}--"
            f"{r['roc_auc_mc_high']:.3f}) & {r['sensitivity']:.3f} & "
            f"{int(r['n_distinct_source_cases'])} / "
            f"{int(r['max_times_one_patient_used'])}$\\times$ \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""]
    return "\n".join(lines)


def external_table(tables: Path) -> str:
    """Transportability probe, generated with PR-AUC alongside ROC-AUC.

    PR-AUC is reported because prevalence differs between the cohorts (0.64
    internally, 0.21 externally). ROC-AUC is invariant to that shift and so
    hides the change in precision a deployer would experience; the no-skill
    PR-AUC baseline is the external prevalence itself.
    """
    path = tables / "table_42_external_validation.csv"
    if not path.is_file():
        return ""
    frame = pd.read_csv(path)
    if "pr_auc" not in frame.columns:
        return ""
    internal = frame[frame["arm"] == "internal_nested_cv"].set_index("model")
    ext = frame[frame["arm"] == "external_frozen_transfer"]
    baseline = float(ext["pr_auc_baseline"].iloc[0])
    label = {"logreg": "Logistic", "svm": "SVM",
             "random_forest": "Random for."}
    lines = [
        "% Generated by scripts/24_make_latex_tables.py -- do not edit.",
        "% Source: reports/tables/table_42_external_validation.csv",
        r"\begin{table}[t]",
        r"\caption{Frozen transfer to an independent cohort "
        r"(\textbf{exploratory}; 94 subjects, 20 cases). Internal reference "
        r"and external result use the same ten variables. PR-AUC is shown "
        r"because prevalence differs between the cohorts (0.64 internally, "
        rf"{baseline:.2f} externally); a no-skill model scores {baseline:.2f}. "
        r"Intervals are stratified patient-level bootstraps of the external "
        r"result only, and are not a paired test of the "
        r"internal--external difference.}",
        r"\label{tab:external}",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{2pt}",
        r"\begin{tabular}{@{}lccc@{}}",
        r"\toprule",
        r"\tabhead{Model} & \tabhead{Int.} & \tabhead{Ext.\ AUC} & "
        r"\tabhead{Ext.\ PR-AUC} \\",
        r" & \tabhead{AUC} & \tabhead{(95\% CI)} & \tabhead{(95\% CI)} \\",
        r"\midrule",
    ]
    for _, r in ext.iterrows():
        name = label.get(r["model"], r["model"])
        int_auc = float(internal.loc[r["model"], "roc_auc"])
        lines.append(
            f"{name} & {int_auc:.3f} & "
            f"{r['roc_auc']:.3f} ({r['roc_auc_ci_low']:.3f}--"
            f"{r['roc_auc_ci_high']:.3f}) & "
            f"{r['pr_auc']:.3f} ({r['pr_auc_ci_low']:.3f}--"
            f"{r['pr_auc_ci_high']:.3f}) \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def null_diagnostics(tables: Path) -> str:
    """Does the copula null preserve what it claims to preserve?"""
    path = tables / "table_53_copula_null_diagnostics.csv"
    summary_path = tables / "table_46_provenance_null_summary.csv"
    if not path.is_file() or not summary_path.is_file():
        return ""
    diag = pd.read_csv(path)
    marg = diag[diag["quantity"] == "marginal"]
    pair = diag[diag["quantity"] == "spearman_pair"]
    nulls = pd.read_csv(summary_path)

    gap = (pair["real"] - pair["null_mean"]).abs()
    off = int(marg["synthetic_values_off_observed_support"].sum())
    lines = [
        "% Generated by scripts/24_make_latex_tables.py -- do not edit.",
        "% Sources: table_53_copula_null_diagnostics.csv,",
        "%          table_46_provenance_null_summary.csv",
        r"\begin{table}[h]",
        r"\caption{Null models actually implemented, and whether the "
        r"dependence-preserving null preserves what it claims. Row-order "
        r"permutation is excluded: bipartite matching is invariant to "
        r"candidate row order, so it is a property of the estimator, not a "
        r"null (Section~S3-B).}",
        r"\label{tab:nulldiag}",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{2pt}",
        r"\begin{tabular}{@{}p{4.1cm}cr@{}}",
        r"\toprule",
        r"\tabhead{Quantity} & \tabhead{Value} & \tabhead{Basis} \\",
        r"\midrule",
    ]
    for _, r in nulls.iterrows():
        label = ("Independent column permutation"
                 if "column" in r["null"] else "Gaussian-copula null")
        lines.append(
            f"{label} & {r['mean']:.3f} $\\pm$ {r['sd']:.3f} & "
            f"{int(r['n_draws'])} draws \\\\")
        lines.append(
            f"\\quad exceedances $\\geq$ observed & "
            f"{int(r['n_at_or_above_observed'])} & "
            f"$p \\leq {r['p_upper_bound']:.3f}$ \\\\")
    lines += [
        r"\midrule",
        f"Variable pairs compared & {len(pair)} & Spearman \\\\",
        f"Mean $|$real $-$ null$|$ correlation & {gap.mean():.3f} & "
        r"retained \\",
        f"Largest single discrepancy & {gap.max():.3f} & "
        rf"\texttt{{{esc(pair.loc[gap.idxmax(), 'term'])}}} \\",
        f"Synthetic values off observed support & {off} & "
        r"exact \\",
        r"\bottomrule", r"\end{tabular}", r"\end{table}", "",
    ]
    return "\n".join(lines)


def literature_summary(tables: Path) -> str:
    """Table I, generated from the literature extraction sheet.

    Previously typed by hand, which is how it came to say that three studies
    validate across the two releases when only one of the three is verifiable
    from its own source text. Rows are labelled by the strength of their
    basis, and the ``verified`` rows are the only ones any claim rests on.
    """
    summary = pd.read_csv(tables / "table_26_prior_work_summary.csv")
    value = dict(zip(summary["quantity"], summary["value"]))
    order = [
        ("n_studies_surveyed", "Studies examined", "our sample"),
        ("n_independently_verified", "Verified from source text",
         "full text / abstract"),
        ("n_verified_metric_geq_099",
         r"Verified headline metrics $\geq 0.99$", "verified"),
        ("n_cross_dataset_VERIFIED_from_source",
         "Cross-release validation, verified", "verified"),
        ("n_merging_releases_VERIFIED_from_source",
         "Merging the releases, verified", "verified"),
        ("n_with_genuinely_external_validation",
         "With a genuinely external cohort", "verified"),
        ("n_cross_dataset_attributed_only",
         "Cross-release validation, attributed only", "attributed"),
        ("n_kabir_coded_sc_egfr_yes",
         "Coded as using creatinine or eGFR", "attributed"),
    ]
    lines = [
        "% Generated by scripts/24_make_latex_tables.py -- do not edit.",
        "% Source: reports/tables/table_26_prior_work_summary.csv",
        r"\begin{table}[t]",
        r"\caption{Targeted illustrative review ($N=13$ studies examined). "
        r"Rows marked \emph{attributed} rest on a published comparison "
        r"table~\cite{kabir2026}, not on our own reading, and support no "
        r"quantitative claim. This is not a systematic sample; no prevalence "
        r"should be inferred from it.}",
        r"\label{tab:lit}",
        r"\centering",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\begin{tabular}{lrl}",
        r"\toprule",
        r"\tabhead{Quantity} & \tabhead{Value} & \tabhead{Basis} \\",
        r"\midrule",
    ]
    for key, label, basis in order:
        if key not in value:
            continue
        lines.append(f"{label} & {int(value[key])} & {basis} \\\\")
    n_paywalled = int(value["n_studies_surveyed"]) - int(
        value["n_independently_verified"])
    lines.append(f"Not accessible (paywalled) & {n_paywalled} & --- \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def leave_one_out(tables: Path) -> str:
    """The complete leave-one-variable-out results, for the supplement.

    The supplement said Table S2 "gives the complete leave-one-variable-out
    results" and then shipped a stub pointing at the CSV. Generating the
    table keeps the promise and keeps the numbers tied to their source.
    """
    frame = pd.read_csv(tables / "table_44_provenance_sensitivity.csv")
    loo = frame[frame["analysis"] == "leave_one_variable_out"].copy()
    loo = loo.sort_values("n_unique_pins")
    lines = [
        "% Generated by scripts/24_make_latex_tables.py -- do not edit.",
        "% Source: reports/tables/table_44_provenance_sensitivity.csv",
        r"\begin{table}[t]",
        r"\caption{Leave-one-variable-out matching, complete results. Each "
        r"row removes one containment variable and re-runs the match. The "
        r"match fraction is 1.000 in every case; \emph{unique pins} is the "
        r"discriminating statistic. Ordered by unique pins, fewest first.}",
        r"\label{tab:loo}",
        r"\centering",
        r"\footnotesize",
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"\tabhead{Variable removed} & \tabhead{$k$} & \tabhead{Match} & "
        r"\tabhead{Unique pins} \\",
        r"\midrule",
    ]
    for _, r in loo.iterrows():
        lines.append(
            rf"\texttt{{{esc(str(r['dropped_variable']))}}} & "
            f"{int(r['n_variables'])} & {r['match_fraction']:.3f} & "
            f"{int(r['n_unique_pins'])} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def inline_numbers(tables: Path) -> str:
    """Macros for the values the manuscript quotes inline.

    Inline numbers are the ones that drift: a table is regenerated when
    the analysis re-runs, but a number typed into a sentence is not. The
    copula-null statistics were quoted from a 100-draw run while the
    stage default is 200, and nothing caught it until the pipeline was
    run end to end. Defining them as macros removes the failure mode.
    """
    nulls = pd.read_csv(tables / "table_46_provenance_nulls.csv")
    copula = nulls["copula_preserving_correlations"]
    column = nulls["column_permutation"]
    observed = 1.0
    out = [
        "% Generated by scripts/24_make_latex_tables.py. Do not edit.",
        "% Source: reports/tables/table_46_provenance_nulls.csv",
    ]

    def macro(name: str, value: str) -> None:
        out.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    macro("NullDraws", str(len(nulls)))
    macro("NullCopulaMean", f"{copula.mean():.3f}")
    macro("NullCopulaSD", f"{copula.std(ddof=1):.3f}")
    macro("NullCopulaMax", f"{copula.max():.3f}")
    macro("NullColumnMean", f"{column.mean():.3f}")
    macro("NullColumnSD", f"{column.std(ddof=1):.3f}")
    macro("NullCopulaSDDistance",
          f"{(observed - copula.mean()) / copula.std(ddof=1):.0f}")

    # Test inventory, written by reproduce.py after the suite runs. Absent
    # on a build that never ran the tests; the manuscript-consistency test
    # then fails rather than letting a stale count stand.
    inventory = tables / "table_52_test_inventory.csv"
    if inventory.is_file():
        counts = pd.read_csv(inventory).iloc[0]
        macro("TestCount", str(int(counts["tests"])))
    return "\n".join(out) + "\n"


def main() -> int:
    cfg = load_config()
    tables_dir = project_root() / cfg["paths"]["tables_dir"]
    OUT.mkdir(parents=True, exist_ok=True)

    registry = pd.read_csv(project_root() / "data" / "feature_registry.csv")
    written = []

    (OUT / "leakage_taxonomy.tex").write_text(
        leakage_taxonomy(registry), encoding="utf-8")
    written.append("leakage_taxonomy.tex")

    (OUT / "registry_summary.tex").write_text(
        registry_summary(registry), encoding="utf-8")
    written.append("registry_summary.tex")
    (OUT / "numbers.tex").write_text(
        inline_numbers(TABLES), encoding="utf-8")
    written.append("numbers.tex")
    (OUT / "leave_one_out.tex").write_text(
        leave_one_out(TABLES), encoding="utf-8")
    written.append("leave_one_out.tex")
    (OUT / "literature_summary.tex").write_text(
        literature_summary(TABLES), encoding="utf-8")
    written.append("literature_summary.tex")
    (OUT / "restricted_full.tex").write_text(
        restricted_full(TABLES / "table_49_restricted_featuresets.csv"),
        encoding="utf-8")
    written.append("restricted_full.tex")
    (OUT / "casemix_simulation.tex").write_text(
        casemix_simulation(TABLES / "table_54_casemix_simulation.csv"),
        encoding="utf-8")
    written.append("casemix_simulation.tex")
    (OUT / "null_diagnostics.tex").write_text(
        null_diagnostics(TABLES), encoding="utf-8")
    written.append("null_diagnostics.tex")
    (OUT / "external_table.tex").write_text(
        external_table(TABLES), encoding="utf-8")
    written.append("external_table.tex")

    fragment = restricted_featuresets(
        tables_dir / "table_49_restricted_featuresets.csv")
    if fragment:
        (OUT / "restricted_featuresets.tex").write_text(fragment, encoding="utf-8")
        written.append("restricted_featuresets.tex")
    else:
        print("  note: table_49 not present; restricted_featuresets.tex skipped")

    for name in written:
        print(f"wrote paper/generated/{name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
